const tables = [
  {
    id: 1,
    name: 'Bàn 1',
    status: '',
    type: 1,
    tableName: 'TABLE_1',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 2,
    name: 'Bàn 2',
    status: '',
    type: 1,
    tableName: 'TABLE_2',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 3,
    name: 'Bàn 3',
    status: '',
    type: 1,
    tableName: 'TABLE_3',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 4,
    name: 'Bàn 4',
    status: '',
    type: 1,
    tableName: 'TABLE_4',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 5,
    name: 'Bàn 5',
    status: '',
    type: 1,
    tableName: 'TABLE_5',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 6,
    name: 'Bàn 6',
    status: '',
    type: 1,
    tableName: 'TABLE_6',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 7,
    name: 'Bàn 7',
    status: '',
    type: 1,
    tableName: 'TABLE_7',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 8,
    name: 'Bàn 8',
    status: '',
    type: 1,
    tableName: 'TABLE_8',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 9,
    name: 'Bàn 9',
    status: '',
    type: 1,
    tableName: 'TABLE_9',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 10,
    name: 'Bàn 10',
    status: '',
    type: 1,
    tableName: 'TABLE_10',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 11,
    name: 'Bàn 11',
    status: '',
    type: 1,
    tableName: 'TABLE_11',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 12,
    name: 'Bàn 12',
    status: '',
    type: 1,
    tableName: 'TABLE_12',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 13,
    name: 'Bàn 13',
    status: '',
    type: 1,
    tableName: 'TABLE_13',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 14,
    name: 'Bàn 14',
    status: '',
    type: 1,
    tableName: 'TABLE_14',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 15,
    name: 'Bàn 15',
    status: '',
    type: 1,
    tableName: 'TABLE_15',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
  {
    id: 16,
    name: 'Bàn 16',
    status: '',
    type: 1,
    tableName: 'TABLE_16',
    idOrder: 0,
    quantity: 0,
    isCheck: false,
  },
];
export default tables;
